name: Run Program

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t port-scanner-cli-java .
      - name: Exec java program
        run: docker run --rm --name port-scanner-cli-java port-scanner-cli-java
